@echo off
echo [Magange] Mendaftarkan authtoken...
C:\laragon\www\ngrok.exe config add-authtoken 3GADRgAdYLS1KgEPAfJ38ou3ZG0_6aevfrXPta659kfEhZeSR
echo Menjalankan ngrok di port 8000...
C:\laragon\www\ngrok.exe http 8000